---
- name: create ip sla
  hosts: 27.27.27.209
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_config:
         lines:
         - udp-jitter 203.199.244.66 1024 source-ip 203.199.244.20 num-packets 500
         - frequency 30
         - history hours-of-statistics-kept 10
         - ip sla schedule 250 life forever start-time now
         parents: ip sla 250
     register: version
   - name: Second Task
     debug:
       var: version
       
   - name: Third Task
     ios_command:
         commands: show running-config
     register: version
   - name: Fourth Task
     debug:
       var: version

       
       
